version = 1
SPDX-PackageName = "qthesis"

[[annotations]]
path = "bibliography.bib"
precedence = "override"
SPDX-FileCopyrightText = "2026 Frank Langbein <frank@langbein.org>"
SPDX-License-Identifier = "LPPL-1.3c"
