#!/usr/bin/env python3
# Build a permuted (obfuscated) font and permutation table for the obfuscate class option.
# Can build obfuscated fonts for sans, serif, or hacker (any input font), including each
# variant (Regular, Bold, Italic, BoldItalic, SmallCaps, Slanted). Use the same --seed
# for all runs so all fonts share obfuscate-perm.lua.
# Output: fonts/<output-font>, fonts/obfuscate-perm.lua
# Usage: python3 scripts/build-hacker-font.py [--seed N] [--font PATH] [--output-dir DIR] [--output-font NAME.otf]
#
# SPDX-FileCopyrightText: 2026 Frank Langbein <frank@langbein.org>
# SPDX-License-Identifier: LPPL-1.3c

import argparse
import random
import sys
from pathlib import Path

PUA_BASE = 0xE000
RANGE_SIZE = 256  # Latin-1


def find_input_font():
    """Find Inconsolata (preferred, consistent with noobfuscate), else Fira Mono, else Liberation Mono."""
    candidates = [
        # Inconsolata – TeX Live (inconsolata-nerd-font: InconsolataLGCNerdFontMono, InconsolataLGCNerdFont)
        Path("/usr/share/texlive/texmf-dist/fonts/truetype/public/inconsolata-nerd-font/InconsolataLGCNerdFontMono-Regular.ttf"),
        Path("/usr/share/texlive/texmf-dist/fonts/truetype/public/inconsolata-nerd-font/InconsolataLGCNerdFont-Regular.ttf"),
        # Inconsolata – system / noobfuscate
        Path("/usr/share/fonts/truetype/inconsolata/Inconsolata-Regular.ttf"),
        Path("/usr/share/fonts/TTF/Inconsolata-Regular.ttf"),
        Path("/usr/share/fonts/opentype/inconsolata/Inconsolata-Regular.otf"),
        Path("/usr/share/fonts/opentype/inconsolata/Inconsolata.otf"),
        Path.home() / ".local/share/fonts/Inconsolata-Regular.ttf",
        Path.home() / ".local/share/fonts/Inconsolata.otf",
        # Fira Mono – TeX Live (fonts in fonts/opentype/public/fira/, not tex/latex/fira/)
        Path("/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Regular.otf"),
        # Fira Mono – system
        Path("/usr/share/fonts/truetype/fira/FiraMono-Regular.ttf"),
        Path("/usr/share/fonts/opentype/fira/FiraMono-Regular.otf"),
        Path.home() / ".local/share/fonts/FiraMono-Regular.ttf",
        # Liberation Mono – last resort
        Path("/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf"),
    ]
    for p in candidates:
        if p.exists():
            return str(p)
    return None


def generate_permutation(seed=None):
    """Return a permutation of range(RANGE_SIZE). perm[c] = code point to use for character c."""
    rng = random.Random(seed)
    perm = list(range(RANGE_SIZE))
    rng.shuffle(perm)
    return perm


def build_permuted_font(input_font_path, perm, output_path):
    """Build a new font with cmap: PUA_BASE + perm[c] -> glyph for c.
    Only PUA code points are in the cmap so PDF ToUnicode uses PUA (copy-paste is obfuscated).
    """
    try:
        from fontTools.ttLib import TTFont
        from fontTools.ttLib.tables._c_m_a_p import CmapSubtable
        from fontTools.ttLib import newTable
    except ImportError:
        print("Error: fontTools is required. Install with: pip install fonttools", file=sys.stderr)
        sys.exit(1)

    font = TTFont(input_font_path)
    orig_cmap = font.getBestCmap()  # unicode -> glyph name
    if orig_cmap is None:
        print("Error: could not get cmap from font", file=sys.stderr)
        sys.exit(1)

    # New cmap: PUA_BASE + perm[c] -> same glyph as c (for c in 0..255 that exist)
    new_cmap_dict = {}
    for c in range(RANGE_SIZE):
        if c in orig_cmap:
            new_cmap_dict[PUA_BASE + perm[c]] = orig_cmap[c]

    # Subtable (3, 1) Windows Unicode BMP - primary for embedding
    sub31 = CmapSubtable.newSubtable(4)
    sub31.platformID = 3
    sub31.platEncID = 1
    sub31.language = 0
    sub31.cmap = dict(new_cmap_dict)

    # Subtable (0, 4) Unicode BMP - so Unicode-based tools see PUA only
    sub04 = CmapSubtable.newSubtable(4)
    sub04.platformID = 0
    sub04.platEncID = 4
    sub04.language = 0
    sub04.cmap = dict(new_cmap_dict)

    cmap_table = newTable("cmap")
    cmap_table.tableVersion = 0
    cmap_table.tables = [sub31, sub04]
    font["cmap"] = cmap_table

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    font.save(output_path)
    font.close()
    print(f"Wrote {output_path}")


def write_perm_lua(perm, output_path):
    """Write permutation as a Lua table: obfuscate_perm[c] = value for c in 0..255."""
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "-- Permutation for hacker obfuscation (generated by build-hacker-font.py).",
        "-- obfuscate_perm[c] = code point offset for character c (0..255).",
        "return {",
    ]
    for c in range(RANGE_SIZE):
        lines.append(f"  [{c}] = {perm[c]},")
    lines.append("}")
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out}")


def main():
    ap = argparse.ArgumentParser(description="Build obfuscated hacker font and permutation table")
    ap.add_argument("--seed", type=int, default=None, help="Random seed for reproducible permutation")
    ap.add_argument("--font", type=str, default=None, help="Path to input font (Inconsolata or Fira Mono)")
    ap.add_argument("--output-dir", type=str, default="fonts", help="Output directory (default: fonts)")
    ap.add_argument("--output-font", type=str, default="hacker-obfuscated.otf", help="Output font filename (default: hacker-obfuscated.otf)")
    args = ap.parse_args()

    font_path = args.font
    if font_path is None:
        font_path = find_input_font()
    if font_path is None:
        print("Error: no input font found. Install Inconsolata (preferred), Fira Mono, or Liberation Mono; or pass --font PATH", file=sys.stderr)
        sys.exit(1)
    if not Path(font_path).exists():
        print(f"Error: font not found: {font_path}", file=sys.stderr)
        sys.exit(1)

    print(f"Using font: {font_path}")
    perm = generate_permutation(args.seed)
    out_dir = Path(args.output_dir)
    build_permuted_font(font_path, perm, out_dir / args.output_font)
    write_perm_lua(perm, out_dir / "obfuscate-perm.lua")


if __name__ == "__main__":
    main()
